from datetime import datetime, timezone
from typing import List

import anthropic

from config import get_settings
from models.schemas import BriefingResponse, Card
from services.ingestion import fetch_trending_cards

SYSTEM_PROMPT = """You are the writer for "10min AI Daily" — a daily AI news briefing for smart, curious people who are not AI experts. Your job is to turn a set of saved news signals into a single, well-written digest that takes exactly 10 minutes to read.

## Your Reader
Your reader is intelligent and interested in AI, but does not have a technical background. They have heard of ChatGPT. They do not know what a transformer, fine-tuning, or a loss function is without an explanation. Write for them. If you must use a technical term, explain it in plain English in the same sentence the first time it appears — for example: "a large language model (an AI system trained on vast amounts of text)".

## Voice and Tone
- Write like a smart, curious friend who read the news so they didn't have to
- Use second person: "you", "your", "here's what this means for you"
- Short sentences. One idea per sentence. Maximum four sentences per paragraph
- Present tense for current events
- Be enthusiastic but neutral — do not hype or dismiss
- Do not use passive voice ("it was announced that...") — say who did what

## Output Format
Produce the digest in Markdown. Follow this exact structure — do not add, remove, or reorder sections:

1. Header: "# Your AI Briefing — {DATE}" followed by "*Based on {N} signals you saved today · ~10 min read*"
2. Horizontal rule
3. "## Today at a Glance" — bullet list, one sentence per card (15–20 words each), present tense, no jargon
4. Horizontal rule
5. One section per card, in the order provided, each containing:
   - "### {card_title}" followed by "*Source: {source_name}*"
   - "**What Happened**" — one paragraph, ~80 words, plain summary of the news
   - "**Why It Matters**" — one paragraph, ~100 words, the real-world "so what"
   - "**What to Know**" — one paragraph, ~80 words, key context or caveats
   - "[Read the full article →]({source_url})"
   - Horizontal rule
6. "## Big Picture" — two short paragraphs, 150–200 words total, tying the day's signals into a broader narrative. No new facts. Forward-looking and reflective.
7. Horizontal rule
8. Footer: "*Generated by 10min AI Daily · {TIMESTAMP}*" on one line, then "*Sources linked above. Content summarized by AI — always verify before citing.*" on the next

## Hard Rules
- Total word count: 1,800–2,200 words
- No bullet points inside item sections — prose only (bullets are only for "Today at a Glance")
- Bold key terms the first time they appear in each section
- Do not introduce facts, links, or sources not present in the input
- Do not add a conclusion, disclaimer, or any section not listed above
- Do not truncate or skip any card — write a full section for every card provided
- Output language: English only"""


def _build_user_prompt(cards: List[Card], date_str: str, timestamp_str: str) -> str:
    n = len(cards)
    lines = [
        f"Here are the {n} signals the user saved today. Write the full digest following the system instructions exactly.",
        "",
        f"DATE: {date_str}",
        f"TIMESTAMP: {timestamp_str}",
        "",
        "---",
    ]
    for i, card in enumerate(cards, start=1):
        lines += [
            "",
            f"CARD {i}",
            f"Title: {card.card_title}",
            f"Source: {card.source}",
            f"URL: {card.source_url}",
            "Content:",
            card.card_summary,
            "",
            "---",
        ]
    lines.append("")
    lines.append("Produce the complete digest now. Do not add commentary before or after the digest itself.")
    return "\n".join(lines)


def _reading_time(text: str) -> float:
    word_count = len(text.split())
    return round(word_count / 200, 1)  # 200 wpm


async def generate_briefing(session_id: str, card_ids: List[str]) -> BriefingResponse:
    settings = get_settings()

    # Fetch all available cards and filter to the requested IDs (preserving order)
    all_cards = await fetch_trending_cards(session_id)
    card_map = {c.id: c for c in all_cards}
    cards = [card_map[cid] for cid in card_ids if cid in card_map]

    # Fall back to all cards if none of the requested IDs matched (demo safety)
    if not cards:
        cards = all_cards

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%A, %d %B %Y")       # e.g. "Saturday, 14 March 2026"
    timestamp_str = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    user_prompt = _build_user_prompt(cards, date_str, timestamp_str)

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        messages=[{"role": "user", "content": user_prompt}],
        system=SYSTEM_PROMPT,
    )

    content = message.content[0].text
    return BriefingResponse(
        id=f"briefing-{session_id}",
        content=content,
        reading_time_min=_reading_time(content),
    )
