import { GraphData, GraphNode, GraphEdge } from '@/types/graph';

const rawNodes: Pick<GraphNode, 'id' | 'label' | 'description' | 'frequency' | 'isToday'>[] = [
  { id: 'n0', label: 'AI Safety', description: 'Practices and frameworks for ensuring AI systems behave safely and as intended.', frequency: 3, isToday: true },
  { id: 'n1', label: 'Alignment', description: 'Ensuring AI systems pursue intended goals without unintended side effects.', frequency: 2, isToday: true },
  { id: 'n2', label: 'Benchmarks', description: 'Standardized tests for evaluating model capabilities and safety properties.', frequency: 1, isToday: true },
  { id: 'n3', label: 'Open Source', description: 'Publicly available model weights, datasets, and evaluation tools.', frequency: 3, isToday: true },
  { id: 'n4', label: 'LLM', description: 'Large language models trained on text data at scale.', frequency: 5, isToday: false },
  { id: 'n5', label: 'Toxicity', description: 'Harmful or offensive content generated by models.', frequency: 1, isToday: true },
  { id: 'n6', label: 'Bias', description: 'Systematic unfairness or skew in model outputs.', frequency: 1, isToday: true },
  { id: 'n7', label: 'Fine-tuning', description: 'Adapting a pre-trained model to specific tasks or domains.', frequency: 2, isToday: false },
  { id: 'n8', label: 'Multimodal', description: 'Models that process and generate both text and images.', frequency: 1, isToday: true },
  { id: 'n9', label: 'GPT-4V', description: 'OpenAI vision-language model with image understanding.', frequency: 1, isToday: true },
  { id: 'n10', label: 'Regulation', description: 'Government policies and frameworks governing AI use.', frequency: 2, isToday: false },
  { id: 'n11', label: 'EU AI Act', description: 'European regulatory framework classifying AI systems by risk.', frequency: 1, isToday: false },
  { id: 'n12', label: 'Evaluation', description: 'Systematic assessment of model performance and behavior.', frequency: 2, isToday: true },
  { id: 'n13', label: 'JSON', description: 'Structured data format used for API responses.', frequency: 1, isToday: true },
  { id: 'n14', label: 'RLHF', description: 'Reinforcement learning from human feedback for alignment.', frequency: 1, isToday: true },
];

const todayEdgeList: [string, string][] = [
  ['n0','n1'],['n0','n2'],['n0','n5'],['n0','n6'],['n0','n12'],
  ['n1','n14'],['n2','n12'],['n5','n6'],['n8','n9'],['n3','n8'],
];

const fullEdgeList: [string, string][] = [
  ['n0','n1'],['n0','n2'],['n0','n5'],['n0','n6'],['n0','n12'],['n0','n4'],
  ['n1','n14'],['n2','n12'],['n2','n4'],['n3','n4'],['n3','n7'],['n3','n8'],
  ['n4','n7'],['n4','n8'],['n4','n9'],['n4','n14'],['n4','n13'],
  ['n5','n6'],['n8','n9'],['n10','n11'],['n10','n0'],['n14','n4'],
];

function toEdges(list: [string, string][]): GraphEdge[] {
  return list.map(([s, t]) => ({ source: s, target: t }));
}

export function buildAdjMap(edges: GraphEdge[]): Record<string, string[]> {
  const adj: Record<string, string[]> = {};
  edges.forEach((e) => {
    if (!adj[e.source]) adj[e.source] = [];
    if (!adj[e.target]) adj[e.target] = [];
    adj[e.source].push(e.target);
    adj[e.target].push(e.source);
  });
  return adj;
}

export function buildSampleGraph(W: number, H: number): GraphData {
  let todayIdx = 0;
  const nodes: GraphNode[] = rawNodes.map((raw) => {
    const baseR = 8 + raw.frequency * 2.5;
    const todayTx = W * 0.3 + Math.random() * W * 0.4;
    const todayTy = H * 0.3 + Math.random() * H * 0.4;
    const fullTx = W * 0.1 + Math.random() * W * 0.8;
    const fullTy = H * 0.08 + Math.random() * H * 0.84;
    const isToday = raw.isToday;
    const delay = isToday ? 20 + todayIdx * 12 : 0;
    if (isToday) todayIdx++;

    return {
      ...raw,
      r: baseR,
      x: isToday ? -20 : fullTx,
      y: isToday ? -20 : fullTy,
      vx: 0, vy: 0,
      todayTx, todayTy, fullTx, fullTy,
      tx: isToday ? todayTx : fullTx,
      ty: isToday ? todayTy : fullTy,
      startX: -20, startY: -20,
      cpx: todayTx * 0.5 + Math.random() * 60,
      cpy: -20 + todayTy * 0.3,
      animT: isToday ? 0 : 1,
      animating: false,
      entered: !isToday,
      settled: !isToday,
      opacity: 0,
      scale: isToday ? 0.3 : 1,
      delay,
      breathPhase: Math.random() * Math.PI * 2,
      breathSpeed: 0.015 + Math.random() * 0.01,
      labelAlpha: 0,
      targetLabelAlpha: 0,
      orbiters: isToday
        ? Array.from({ length: 2 + Math.floor(Math.random() * 2) }, () => ({
            angle: Math.random() * Math.PI * 2,
            speed: 0.02 + Math.random() * 0.02,
            dist: baseR * 1.8 + Math.random() * 6,
            size: 1.2 + Math.random(),
          }))
        : [],
    };
  });

  return {
    nodes,
    todayEdges: toEdges(todayEdgeList),
    fullEdges: toEdges(fullEdgeList),
  };
}
