import { GraphData, GraphNode, GraphEdge } from '@/types/graph';

const rawNodes: Pick<GraphNode, 'id' | 'label' | 'description' | 'frequency' | 'isToday'>[] = [
  { id: 'n0', label: 'AI Safety', description: 'Practices and frameworks for ensuring AI systems behave safely and as intended.', frequency: 3, isToday: true },
  { id: 'n1', label: 'Alignment', description: 'Ensuring AI systems pursue intended goals without unintended side effects.', frequency: 2, isToday: true },
  { id: 'n2', label: 'Benchmarks', description: 'Standardized tests for evaluating model capabilities and safety properties.', frequency: 1, isToday: true },
  { id: 'n3', label: 'Open Source', description: 'Publicly available model weights, datasets, and evaluation tools.', frequency: 3, isToday: true },
  { id: 'n4', label: 'LLM', description: 'Large language models trained on text data at scale.', frequency: 5, isToday: false },
  { id: 'n5', label: 'Toxicity', description: 'Harmful or offensive content generated by models.', frequency: 1, isToday: true },
  { id: 'n6', label: 'Bias', description: 'Systematic unfairness or skew in model outputs.', frequency: 1, isToday: true },
  { id: 'n7', label: 'Fine-tuning', description: 'Adapting a pre-trained model to specific tasks or domains.', frequency: 2, isToday: false },
  { id: 'n8', label: 'Multimodal', description: 'Models that process and generate both text and images.', frequency: 1, isToday: true },
  { id: 'n9', label: 'GPT-4V', description: 'OpenAI vision-language model with image understanding.', frequency: 1, isToday: true },
  { id: 'n10', label: 'Regulation', description: 'Government policies and frameworks governing AI use.', frequency: 2, isToday: false },
  { id: 'n11', label: 'EU AI Act', description: 'European regulatory framework classifying AI systems by risk.', frequency: 1, isToday: false },
  { id: 'n12', label: 'Evaluation', description: 'Systematic assessment of model performance and behavior.', frequency: 2, isToday: true },
  { id: 'n13', label: 'JSON', description: 'Structured data format used for API responses.', frequency: 1, isToday: true },
  { id: 'n14', label: 'RLHF', description: 'Reinforcement learning from human feedback for alignment.', frequency: 1, isToday: true },
];

const rawEdges: GraphEdge[] = [
  { source: 'n0', target: 'n1', relationship: 'related_to' },
  { source: 'n0', target: 'n2', relationship: 'related_to' },
  { source: 'n0', target: 'n5', relationship: 'mentions' },
  { source: 'n0', target: 'n6', relationship: 'mentions' },
  { source: 'n0', target: 'n12', relationship: 'related_to' },
  { source: 'n0', target: 'n4', relationship: 'related_to' },
  { source: 'n1', target: 'n14', relationship: 'builds_on' },
  { source: 'n2', target: 'n12', relationship: 'overlaps_with' },
  { source: 'n2', target: 'n4', relationship: 'related_to' },
  { source: 'n3', target: 'n4', relationship: 'related_to' },
  { source: 'n3', target: 'n7', relationship: 'related_to' },
  { source: 'n3', target: 'n8', relationship: 'related_to' },
  { source: 'n4', target: 'n7', relationship: 'related_to' },
  { source: 'n4', target: 'n8', relationship: 'related_to' },
  { source: 'n4', target: 'n9', relationship: 'related_to' },
  { source: 'n4', target: 'n14', relationship: 'related_to' },
  { source: 'n4', target: 'n13', relationship: 'related_to' },
  { source: 'n5', target: 'n6', relationship: 'overlaps_with' },
  { source: 'n8', target: 'n9', relationship: 'builds_on' },
  { source: 'n10', target: 'n11', relationship: 'builds_on' },
  { source: 'n10', target: 'n0', relationship: 'related_to' },
  { source: 'n14', target: 'n4', relationship: 'related_to' },
];

export function buildSampleGraph(canvasW: number, canvasH: number): GraphData {
  var todayIdx = 0;
  const nodes: GraphNode[] = rawNodes.map((raw) => {
    const baseR = 8 + raw.frequency * 2.5;
    const tx = canvasW * 0.15 + Math.random() * canvasW * 0.7;
    const ty = canvasH * 0.1 + Math.random() * canvasH * 0.8;

    const isToday = raw.isToday;
    const delay = isToday ? 30 + todayIdx * 12 : 0;
    if (isToday) todayIdx++;

    return {
      ...raw,
      // Position: today nodes start at top-left corner, previous start at target
      x: isToday ? -20 : tx,
      y: isToday ? -20 : ty,
      vx: 0,
      vy: 0,
      r: baseR,
      breathPhase: Math.random() * Math.PI * 2,
      breathSpeed: 0.015 + Math.random() * 0.01,
      labelAlpha: 0,
      targetLabelAlpha: 0,
      orbiters: isToday
        ? Array.from({ length: 2 + Math.floor(Math.random() * 2) }, () => ({
            angle: Math.random() * Math.PI * 2,
            speed: 0.02 + Math.random() * 0.02,
            dist: baseR * 1.8 + Math.random() * 6,
            size: 1.2 + Math.random(),
          }))
        : [],
      // Entrance animation
      tx,
      ty,
      cpx: tx * 0.5 + Math.random() * 60,          // arc control point
      cpy: -20 + ty * 0.3,                           // arc control point
      animT: isToday ? 0 : 1,
      animating: false,
      entered: !isToday ? true : false,
      settled: !isToday ? true : false,
      opacity: isToday ? 0 : 0,                      // previous nodes also start at 0 for fade-in
      scale: isToday ? 0.3 : 1,
      delay,
    };
  });
  return { nodes, edges: rawEdges };
}

export function buildAdjMap(nodes: GraphNode[], edges: GraphEdge[]): Record<string, string[]> {
  const adj: Record<string, string[]> = {};
  nodes.forEach((n) => (adj[n.id] = []));
  edges.forEach((e) => {
    if (adj[e.source]) adj[e.source].push(e.target);
    if (adj[e.target]) adj[e.target].push(e.source);
  });
  return adj;
}
